### ISSUE TITLE
cannot apply cert for customer domain

### ISSUE THREAD

**Issue by latituder** [gardener/gardener-extension-shoot-cert-service#23]
**What happened**:
The secret cannot be generated on a LB svc, which is use for ingress-contrller with a custom DNS.
got event `Normal  cert-annotation       39s                cert-controller-manager  ingresscontroller-service-tls-secret: no certcontrollers running?`

**What you expected to happen**:
can generate a secret with the tls cert

**How to reproduce it (as minimally and precisely as possible)**:
use annotation "cert.gardener.cloud/secretname" to apply a TLS cert for ingress-controller svc, which is using a custom DNS;

**Anything else we need to know?**:
`level=warning msg="updating status failed with: Certificate.cert.gardener.cloud \"ingressnginx-nginx-ingress-controller-service-4zshd\" is invalid: status.lastPendingTimestamp: Invalid value: \"null\": status.lastPendingTimestamp in body must be of type string: \"null\""`

The offending line in the crd is probably
```
            required:
            - lastPendingTimestamp
```
**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Should be fixed with v1.6.3 release - ref https://github.com/gardener/gardener-extension-shoot-cert-service/releases/tag/v1.6.3. Can you verify?

**Comment by MartinWeindel** [comment]
yes fixed with #22
