### ISSUE TITLE
404 Issue

### ISSUE THREAD

**Issue by ujwaliyer** [gardener/gardener-extension-shoot-cert-service#99]
Hi Team- The list of pre-pointers in this [link](https://gardener.cloud/docs/extensions/others/gardener-extension-shoot-cert-service/docs/tutorial-custom-domain-with-istio/) are all leading to 404 errors. Can you please correct the links? Thanks!
![image](https://user-images.githubusercontent.com/5562229/142400378-2b5e652d-be9e-43ad-baef-f96b60dc6c14.png)

**Comment by Kristian-ZH** [comment]
/cc @n-boshnakov

Niki can you please find the github paths of these links and fix them?

**Comment by n-boshnakov** [comment]
> /cc @n-boshnakov
> 
> Niki can you please find the github paths of these links and fix them?

Of course. 

I opened a [PR](https://github.com/gardener/gardener-extension-shoot-cert-service/pull/100) with the changes.
